// Auto-generated bylaw URL and title mappings
// Generated on 2025-03-21T00:00:00.000Z
// Do not edit manually - use generate-bylaw-url-map.ts to update

export const knownBylawUrls: Record<string, string> = {
  "4892": "https://www.oakbay.ca/wp-content/uploads/2025/02/4892-Amenity-Cost-Charge-Bylaw.pdf",
  "4891": "https://www.oakbay.ca/wp-content/uploads/2025/02/4891-Development-Cost-Charge-Bylaw-2024.pdf",
  "4861": "https://www.oakbay.ca/wp-content/uploads/2025/02/4861-Tax-Rates-Bylaw.pdf",
  "4247": "https://www.oakbay.ca/wp-content/uploads/2024/03/4247-Building-and-Plumbing-Bylaw-2005-CONSOLIDATED.pdf",
  "4742": "https://www.oakbay.ca/wp-content/uploads/2024/01/4742-Tree-Protection-Bylaw-2020-CONSOLIDATED.pdf"
};

export const bylawTitleMap: Record<string, string> = {
  "4892": "Amenity Cost Charge Bylaw",
  "4891": "Development Cost Charge Bylaw",
  "4861": "Tax Rates Bylaw, 2024",
  "4247": "Building and Plumbing Bylaw",
  "4742": "Tree Protection Bylaw"
};

// List of all known bylaw numbers
export const VALIDATED_BYLAWS: string[] = [
  "4892",
  "4891",
  "4861",
  "4247",
  "4742"
];